{
  "schema_version": "1.2.0",
  "id": "GHSA-p2c4-gxp4-j3xp",
  "modified": "2021-06-17T18:44:36Z",
  "published": "2021-06-21T17:11:25Z",
  "aliases": [
    "CVE-2021-34801"
  ],
  "summary": "Denial of service",
  "details": "Valine 1.4.14 allows remote attackers to cause a denial of service (application outage) by supplying a ua (aka User-Agent) value that only specifies the product and version.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "npm",
        "name": "valine"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "database_specific": {
        "last_known_affected_version_range": "<= 1.4.14"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34801"
    },
    {
      "type": "WEB",
      "url": "https://github.com/xCss/Valine/issues/366"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-241",
      "CWE-94"
    ],
    "severity": "MODERATE",
    "github_reviewed": true
  }
}