{
  "schema_version": "1.2.0",
  "id": "GHSA-vfmf-vjx2-868p",
  "modified": "2022-02-12T00:01:20Z",
  "published": "2022-02-12T00:01:20Z",
  "aliases": [
    "CVE-2022-0393"
  ],
  "details": "Out-of-bounds Read in Conda vim prior to 8.2.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-0393"
    },
    {
      "type": "WEB",
      "url": "https://github.com/vim/vim/commit/a4bc2dd7cccf5a4a9f78b58b6f35a45d17164323"
    },
    {
      "type": "WEB",
      "url": "https://huntr.dev/bounties/ecc8f488-01a0-477f-848f-e30b8e524bba"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UFXFAILMLUIK4MBUEZO4HNBNKYZRJ5AP/"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}