{
  "schema_version": "1.3.0",
  "id": "GHSA-h865-4c46-jfqg",
  "modified": "2022-05-24T19:04:12Z",
  "published": "2022-05-24T19:04:12Z",
  "aliases": [
    "CVE-2020-36387"
  ],
  "details": "An issue was discovered in the Linux kernel before 5.8.2. fs/io_uring.c has a use-after-free related to io_async_task_func and ctx reference holding, aka CID-6d816e088c35.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-36387"
    },
    {
      "type": "WEB",
      "url": "https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.8.2"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6d816e088c359866f9867057e04f244c608c42fe"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20210727-0006/"
    },
    {
      "type": "WEB",
      "url": "https://sites.google.com/view/syzscope/kasan-use-after-free-read-in-io_async_task_func"
    },
    {
      "type": "WEB",
      "url": "https://syzkaller.appspot.com/bug?id=ce5f07d6ec3b5050b8f0728a3b389aa510f2591b"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-416"
    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}