{
  "schema_version": "1.3.0",
  "id": "GHSA-w32h-m3r8-mq4c",
  "modified": "2022-12-22T15:30:21Z",
  "published": "2022-12-18T06:31:09Z",
  "aliases": [
    "CVE-2022-47516"
  ],
  "details": "An issue was discovered in the libsofia-sip fork in drachtio-server before 0.8.20. It allows remote attackers to cause a denial of service (daemon crash) via a crafted UDP message that leads to a failure of the libsofia-sip-ua/tport/tport.c self assertion.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-47516"
    },
    {
      "type": "WEB",
      "url": "https://github.com/drachtio/drachtio-server/issues/244"
    },
    {
      "type": "WEB",
      "url": "https://github.com/davehorton/sofia-sip/commit/13b2a135287caa2d67ac6cd5155626821e25b377"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-617"
    ],
    "severity": "HIGH",
    "github_reviewed": false
  }
}