{
  "schema_version": "1.2.0",
  "id": "GHSA-pm55-qfxr-h247",
  "modified": "2022-08-19T00:00:16Z",
  "published": "2022-08-19T00:00:16Z",
  "aliases": [
    "CVE-2020-36599"
  ],
  "details": "lib/omniauth/failure_endpoint.rb in OmniAuth before 2.0 does not escape the message_key value.",
  "severity": [

  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-36599"
    },
    {
      "type": "WEB",
      "url": "https://github.com/omniauth/omniauth/commit/43a396f181ef7d0ed2ec8291c939c95e3ed3ff00#diff-575abda9deb9b1a77bf534e898a923029b9a61e991d626db88dc6e8b34260aa2"
    }
  ],
  "database_specific": {
    "cwe_ids": [

    ],
    "severity": null,
    "github_reviewed": false
  }
}